### ISSUE TITLE
RC1 Release Checklist

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/covasim#194]
- [x] Cut a release branch and tag (@lgeorge-idm)
- [x] Write release notes (@cliffckerr)
- [x] Grab screenshot for InfoHub (@lgeorge-idm)
- [x] Update Docker container at https://hub.docker.com/r/idmod/covasim (@devclinton)
- [x] Publish Python package on PyPi (@cliffckerr)
- [x] Deploy to Azure (@John-Sheppard )
- [ ] Confirm site is up and working as expected (@mfisher-idmod and @CWiswell-IDM )

**Comment by lgeorge-idm** [comment]
Release branch at https://github.com/InstituteforDiseaseModeling/covasim/releases/tag/v0.29.8

**Comment by lgeorge-idm** [comment]
@bryanressler-idmod, screenshots:
![covasim-post-execution_panel-open](https://user-images.githubusercontent.com/43424134/80545538-79208580-8968-11ea-85d2-9a67164799aa.png)

![covasim-post-execution-graphs](https://user-images.githubusercontent.com/43424134/80545549-850c4780-8968-11ea-8b84-3d0c1f81d380.png)
